import { StyleSheet } from 'react-native';
import { rem } from '../../utils/constants';

const styles = StyleSheet.create({
	/** margin */
	m1: { margin: rem(0.25) },
	m2: { margin: rem(0.5) },
	m3: { margin: rem(1) },
	m4: { margin: rem(1.5) },
	m5: { margin: rem(3) },

	mt1: { marginTop: rem(0.25) },
	mt2: { marginTop: rem(0.5) },
	mt3: { marginTop: rem(1) },
	mt4: { marginTop: rem(1.5) },
	mt5: { marginTop: rem(3) },

	mr1: { marginRight: rem(0.25) },
	mr2: { marginRight: rem(0.5) },
	mr3: { marginRight: rem(1) },
	mr4: { marginRight: rem(1.5) },
	mr5: { marginRight: rem(3) },

	mb1: { marginBottom: rem(0.25) },
	mb2: { marginBottom: rem(0.5) },
	mb3: { marginBottom: rem(1) },
	mb4: { marginBottom: rem(1.5) },
	mb5: { marginBottom: rem(3) },

	ml1: { marginLeft: rem(0.25) },
	ml2: { marginLeft: rem(0.5) },
	ml3: { marginLeft: rem(1) },
	ml4: { marginLeft: rem(1.5) },
	ml5: { marginLeft: rem(3) },

	my1: { marginVertical: rem(0.25) },
	my2: { marginVertical: rem(0.5) },
	my3: { marginVertical: rem(1) },
	my4: { marginVertical: rem(1.5) },
	my5: { marginVertical: rem(3) },

	mx1: { marginHorizontal: rem(0.25) },
	mx2: { marginHorizontal: rem(0.5) },
	mx3: { marginHorizontal: rem(1) },
	mx4: { marginHorizontal: rem(1.5) },
	mx5: { marginHorizontal: rem(3) },

	/** negative margin */

	mn1: { margin: rem(-0.25) },
	mn2: { margin: rem(-0.5) },
	mn3: { margin: rem(-1) },
	mn4: { margin: rem(-1.5) },
	mn5: { margin: rem(-3) },

	mtn1: { marginTop: rem(-0.25) },
	mtn2: { marginTop: rem(-0.5) },
	mtn3: { marginTop: rem(-1) },
	mtn4: { marginTop: rem(-1.5) },
	mtn5: { marginTop: rem(-3) },

	mrn1: { marginRight: rem(-0.25) },
	mrn2: { marginRight: rem(-0.5) },
	mrn3: { marginRight: rem(-1) },
	mrn4: { marginRight: rem(-1.5) },
	mrn5: { marginRight: rem(-3) },

	mbn1: { marginBottom: rem(-0.25) },
	mbn2: { marginBottom: rem(-0.5) },
	mbn3: { marginBottom: rem(-1) },
	mbn4: { marginBottom: rem(-1.5) },
	mbn5: { marginBottom: rem(-3) },

	mln1: { marginLeft: rem(-0.25) },
	mln2: { marginLeft: rem(-0.5) },
	mln3: { marginLeft: rem(-1) },
	mln4: { marginLeft: rem(-1.5) },
	mln5: { marginLeft: rem(-3) },

	/** padding  */
	p1: { padding: rem(0.25) },
	p2: { padding: rem(0.5) },
	p3: { padding: rem(1) },
	p4: { padding: rem(1.5) },
	p5: { padding: rem(3) },

	pt1: { paddingTop: rem(0.25) },
	pt2: { paddingTop: rem(0.5) },
	pt3: { paddingTop: rem(1) },
	pt4: { paddingTop: rem(1.5) },
	pt5: { paddingTop: rem(3) },

	pr1: { paddingRight: rem(0.25) },
	pr2: { paddingRight: rem(0.5) },
	pr3: { paddingRight: rem(1) },
	pr4: { paddingRight: rem(1.5) },
	pr5: { paddingRight: rem(3) },

	pb1: { paddingBottom: rem(0.25) },
	pb2: { paddingBottom: rem(0.5) },
	pb3: { paddingBottom: rem(1) },
	pb4: { paddingBottom: rem(1.5) },
	pb5: { paddingBottom: rem(3) },

	pl1: { paddingLeft: rem(0.25) },
	pl2: { paddingLeft: rem(0.5) },
	pl3: { paddingLeft: rem(1) },
	pl4: { paddingLeft: rem(1.5) },
	pl5: { paddingLeft: rem(3) },

	py1: { paddingVertical: rem(0.25) },
	py2: { paddingVertical: rem(0.5) },
	py3: { paddingVertical: rem(1) },
	py4: { paddingVertical: rem(1.5) },
	py5: { paddingVertical: rem(3) },

	px1: { paddingHorizontal: rem(0.25) },
	px2: { paddingHorizontal: rem(0.5) },
	px3: { paddingHorizontal: rem(1) },
	px4: { paddingHorizontal: rem(1.5) },
	px5: { paddingHorizontal: rem(3) }
});

export const {
	m1,
	m2,
	m3,
	m4,
	m5,
	mt1,
	mt2,
	mt3,
	mt4,
	mt5,
	mr1,
	mr2,
	mr3,
	mr4,
	mr5,
	mb1,
	mb2,
	mb3,
	mb4,
	mb5,
	ml1,
	ml2,
	ml3,
	ml4,
	ml5,
	my1,
	my2,
	my3,
	my4,
	my5,
	mx1,
	mx2,
	mx3,
	mx4,
	mx5,
	mn1,
	mn2,
	mn3,
	mn4,
	mn5,
	mtn1,
	mtn2,
	mtn3,
	mtn4,
	mtn5,
	mrn1,
	mrn2,
	mrn3,
	mrn4,
	mrn5,
	mbn1,
	mbn2,
	mbn3,
	mbn4,
	mbn5,
	mln1,
	mln2,
	mln3,
	mln4,
	mln5,
	p1,
	p2,
	p3,
	p4,
	p5,
	pt1,
	pt2,
	pt3,
	pt4,
	pt5,
	pr1,
	pr2,
	pr3,
	pr4,
	pr5,
	pb1,
	pb2,
	pb3,
	pb4,
	pb5,
	pl1,
	pl2,
	pl3,
	pl4,
	pl5,
	py1,
	py2,
	py3,
	py4,
	py5,
	px1,
	px2,
	px3,
	px4,
	px5
} = styles;
